"""unique tg id

Revision ID: 4a372e869e73
Revises: e2e320b704cd
Create Date: 2024-11-17 22:16:51.155950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a372e869e73'
down_revision: Union[str, None] = 'e2e320b704cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    # ### end Alembic commands ###
